export enum Env {
  PORT = "PORT",
  RESPAWN_INTERVAL = "RESPAWN_INTERVAL",

  POCKETBASE_BASE_URL = "POCKETBASE_BASE_URL",
  POCKETBASE_USER = "POCKETBASE_USER",
  POCKETBASE_PASSWORD = "POCKETBASE_PASSWORD",

  NOTION_ACCESS_TOKEN = "NOTION_ACCESS_TOKEN",
  NOTION_DATABASE_ID = "NOTION_DATABASE_ID",
}
